version: '3.8'
services:
  app:
    container_name: puttputtpal-front
    image: index.docker.io/mcanziani1/puttputtpal-front:latest
    environment:
      - API_HOST=https://puttputtpal.com
    networks:
      - puttputtpal_net
    ports:
      - "3000:80"
    volumes:
      - /var/log/puttputtpal-front:/var/log/puttputtpal-front
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  puttputtpal_net:
    external: true
# create network externally with docker network create puttputtpal_net
