name: putt_putt_pal
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  numberpicker: ^2.1.2
  flutter_riverpod: ^2.4.10
  touchable: ^1.0.2
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5
  http: ^1.2.0
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.5
  socket_io_client: ^3.0.0-beta.2
  logger: ^2.3.0
  web: 0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.4.0
  freezed: ^2.4.7
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf