lane :beta do
    increment_build_number(
      xcodeproj: "Runner.xcodeproj"
    )
  
    increment_version_number(
      bump_type: "patch"
    )
  
    build_app(scheme: "Runner")
  
    upload_to_testflight
  end
  