lane :beta do
  increment_build_number(
    xcodeproj: "Runner.xcodeproj"
  )
  increment_version_number(
    xcodeproj: "Runner.xcodeproj",
    bump_type: "patch"
  )
  build_app(
    scheme: "Runner",
    export_options: {
      signingStyle: "automatic",
      provisioningProfiles: {
        "com.canziani.puttputtpal" => "match Development com.canziani.puttputtpal"
      }
    },
    xcargs: "-allowProvisioningUpdates"
  )
  upload_to_testflight
end
