name: Build and Deploy iOS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  FLUTTER_CHANNEL: "stable"
  RUBY_VERSION: "3.3.4"

jobs:
  build_ios:
    name: Build iOS
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruby Gems
        run: bundle install
        working-directory: ios

      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version-file: 'pubspec.yaml'
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Fastlane
        run: bundle exec fastlane release_app_store
        working-directory: ios
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
          API_HOST: ${{ secrets.API_HOST }}
