name: Build and Deploy iOS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-deploy-ios:
    name: Build and Deploy iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign --dart-define=API_HOST=${{ secrets.API_HOST }}

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Decode the certificate
        run: echo "${{ secrets.P12_BASE64 }}" | base64 --decode > ./ios/Certificates.p12
      
      - name: Set up Keychain
        run: |
          security create-keychain -p "temp" build.keychain
          security set-keychain-settings -lut 21600 build.keychain
          security unlock-keychain -p "temp" build.keychain
          security import ./ios/Certificates.p12 -k build.keychain -P ${{ secrets.P12_PASSWORD }} -T /usr/bin/codesign
          security list-keychains -d user -s build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k temp build.keychain

      - name: Build and Deploy to TestFlight
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        run: |
          cd ios
          fastlane beta

      - name: Clean Up Keychain
        run: security delete-keychain build.keychain
